# Generated by Django 5.2.17 on 2026-09-18 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_client_id', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('stock_total', models.DecimalField(decimal_places=4, max_digits=24)),
                ('stock_reserved', models.DecimalField(decimal_places=4, max_digits=24)),
                ('stock_available', models.DecimalField(decimal_places=4, max_digits=24)),
                ('received_units', models.DecimalField(decimal_places=4, max_digits=24)),
                ('shipped_units', models.DecimalField(decimal_places=4, max_digits=24)),
                ('active_orders', models.PositiveIntegerField()),
                ('active_receivings', models.PositiveIntegerField()),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('wms_client_id', 'date'), name='one_metric_per_client_day')],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_client_id', models.PositiveBigIntegerField(db_index=True)),
                ('body', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_client_id', models.PositiveBigIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'wms_client_id'), name='one_active_watch_per_user_client')],
            },
        ),
    ]
